### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [ktraw2/TVBot#3]
Can u Make the tv bot mention certain role or name when certain tv show air

**Comment by ktraw2** [comment]
Implemented into the bot - just run `tv!configurenotifications`, and the bot will direct you on how you can now add custom text to your notifications. See commit [e90d08e](https://github.com/ktraw2/TVBot/commit/e90d08ef0c71f050d3b8c6efe23634422e53a039) for code.
